"""Pydantic response schemas for session endpoints."""

import datetime

from pydantic import BaseModel, ConfigDict, Field
from pydantic.alias_generators import to_camel

from models.session import SessionStatus


class SessionResponse(BaseModel):
    """A session as returned by the API, serialized with camelCase field names."""

    model_config = ConfigDict(
        alias_generator=to_camel, populate_by_name=True, from_attributes=True
    )

    id: str = Field(description="UUID v4 generated by the server on session creation.")
    user_id: str = Field(description="The owning user's ID.")
    target: str = Field(description="Target of the pentest (host, URL, or IP).")
    status: SessionStatus = Field(description="Current lifecycle status of the session.")
    report_path: str | None = Field(
        description="Path to the generated Markdown report, set on completion."
    )
    created_at: datetime.datetime = Field(description="Timestamp of session creation.")
    updated_at: datetime.datetime = Field(description="Timestamp of the most recent update.")
