"""ORM model for `ares_sessions.sessions`."""

import datetime
import enum

from sqlalchemy import DateTime, Enum, Index, String, Text, func, text
from sqlalchemy.orm import DeclarativeBase, Mapped, mapped_column


class SessionsBase(DeclarativeBase):
    """Declarative base for models living in the `ares_sessions` database."""


class SessionStatus(enum.StrEnum):
    """Lifecycle status of an agent session."""

    RUNNING = "running"
    COMPLETED = "completed"
    FAILED = "failed"


class Session(SessionsBase):
    """An autonomous pentesting session run by the agent.

    Attributes:
        id: UUID v4 generated by the server on session creation.
        user_id: References `ares_config.users.id` (application-level FK only).
        target: The target of the pentest (host, URL, or IP).
        status: Current lifecycle status of the session.
        report_path: Path to the generated Markdown report, set on completion.
        created_at: Timestamp of session creation.
        updated_at: Timestamp of the most recent update.
    """

    __tablename__ = "sessions"
    __table_args__ = (Index("idx_user_id", "user_id"),)

    id: Mapped[str] = mapped_column(String(36), primary_key=True)
    user_id: Mapped[str] = mapped_column(String(128), nullable=False)
    target: Mapped[str] = mapped_column(String(255), nullable=False)
    status: Mapped[SessionStatus] = mapped_column(
        Enum(SessionStatus, values_callable=lambda e: [m.value for m in e]),
        nullable=False,
        default=SessionStatus.RUNNING,
    )
    report_path: Mapped[str | None] = mapped_column(Text, nullable=True)
    created_at: Mapped[datetime.datetime] = mapped_column(
        DateTime, nullable=False, server_default=text("CURRENT_TIMESTAMP")
    )
    updated_at: Mapped[datetime.datetime] = mapped_column(
        DateTime,
        nullable=False,
        server_default=text("CURRENT_TIMESTAMP"),
        onupdate=func.now(),
    )
